displayName: "Org ID Auth Plugin"
type: middleware

import: github.com/carlosvillanua/orgidauthplugin

summary: "Plugin to validate client IP against organization-specific allowed IPs stored in Valkey/Redis"

testData:
  redisAddr: "valkey-redis-master.traefik.svc.cluster.local:6379"
  redisUsername: "default"
  redisPassword: "traefik"
  orgHeader: "X-Org"
  poolSize: 500
  maxConnIdleTime: "5m"
  poolWaitTimeout: "500ms"
  cacheTTL: "10m"
  cacheMaxSize: 100000
  clusterMode: true
  tlsMode: "secure"
  keyPrefix: "uuid"
  failOpen: true
  requestTimeout: "5s"